apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: tripviewer
        image: registryrmc7467.azurecr.io/tripviewer:v1
        ports:
        - containerPort: 80
        env:
        - name: TRIPS_API_ENDPOINT
          value: http://tripapi.api
        - name: USERPROFILE_API_ENDPOINT
          value: http://userprofile.api
        - name: ASPNETCORE_ENVIRONMENT 
          value: Development
        
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  namespace: web
spec:
  ports:
  - port: 80
  selector:
    app: tripviewer