apiVersion: apps/v1
kind: Deployment
metadata:
  name: userapi
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userapi
  template:
    metadata:
      labels:
        app: userapi
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: userapi
        image: registryrmc7467.azurecr.io/userapi:v1
        ports:
        - containerPort: 80
        env:
        - name: SQL_SERVER
          value: sqlserverrmc7467.database.windows.net
        - name: SQL_USER
          valueFrom: 
            secretKeyRef: 
              name: newsecret 
              key: sqluser 
        volumeMounts:
          - name: secrets-store01-inline
            mountPath: "/secrets"
            readOnly: true
      volumes:
      - name: secrets-store01-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-kvname-user-msi"
---
apiVersion: v1
kind: Service
metadata:
  name: userapi
  namespace: api
spec:
  ports:
  - port: 80
  selector:
    app: userapi